### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [2]:
np.random.rand(4, 5, 3)

array([[[0.33521405, 0.67032435, 0.95210159],
        [0.10189175, 0.18462676, 0.68322972],
        [0.75113847, 0.03295967, 0.61166786],
        [0.10883094, 0.93890401, 0.76204511],
        [0.57901197, 0.73072683, 0.08797744]],

       [[0.70088029, 0.58841604, 0.46029039],
        [0.61576024, 0.90705251, 0.97710094],
        [0.49384285, 0.59526405, 0.87046264],
        [0.38226599, 0.22740642, 0.6362327 ],
        [0.10066368, 0.8231694 , 0.92015193]],

       [[0.97867636, 0.59106034, 0.82802595],
        [0.17190385, 0.29713434, 0.59724309],
        [0.21062594, 0.79539057, 0.3871071 ],
        [0.27762405, 0.50572248, 0.39445679],
        [0.4893706 , 0.50637938, 0.39238774]],

       [[0.6533879 , 0.351156  , 0.13421354],
        [0.83289202, 0.76284595, 0.76582552],
        [0.97809253, 0.14329686, 0.04583578],
        [0.33741319, 0.3678568 , 0.58969611],
        [0.41732719, 0.87047335, 0.30592573]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [3]:
np.random.randn(5)

array([ 0.35313179,  0.51184094, -0.34175882,  1.41598275, -0.49429069])

In [4]:
np.random.randn(3, 4, 2) #정규분포이기 때문에 음수도 가짐

array([[[ 0.18051065, -0.23327228],
        [-0.9665297 , -0.75642021],
        [-0.11424347,  1.09038174],
        [-1.35937881, -0.7295231 ]],

       [[ 0.45731576, -0.14717469],
        [ 0.65136006,  1.06994426],
        [-0.1809659 , -0.984676  ],
        [ 1.75613071, -0.84801614]],

       [[-0.5859222 , -1.21304495],
        [-0.03862134,  2.10877663],
        [-0.28770843,  2.22195802],
        [ 3.49531891,  0.27530504]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [5]:
np.random.randint(1, 100, size=(5,))

array([84, 93, 88,  3, 96])

In [8]:
np.random.randint(1,10, size =(5,3,3))

array([[[1, 2, 7],
        [8, 9, 4],
        [1, 3, 8]],

       [[8, 8, 2],
        [1, 2, 1],
        [9, 5, 7]],

       [[7, 6, 1],
        [5, 4, 4],
        [6, 7, 2]],

       [[1, 8, 5],
        [8, 4, 8],
        [1, 2, 2]],

       [[4, 4, 8],
        [1, 8, 5],
        [4, 2, 1]]])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [24]:
np.random.seed(3)
np.random.randn(3, 4)

array([[ 1.78862847,  0.43650985,  0.09649747, -1.8634927 ],
       [-0.2773882 , -0.35475898, -0.08274148, -0.62700068],
       [-0.04381817, -0.47721803, -1.31386475,  0.88462238]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [25]:
np.random.choice(100, size=(3, 4))

array([[22, 66,  2, 63],
       [60,  1, 51, 90],
       [69, 97, 29, 24]])

In [41]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2, 2), replace=False)

array([[2. , 3. ],
       [4.9, 1.5]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [42]:
np.random.uniform(1.0, 3.0, size=(4, 5)) #2개의 숫자 사이의 랜덤 실수를 리턴합니다.

array([[1.96489161, 1.05205254, 2.01114812, 2.83606004, 1.41393226],
       [2.85146557, 1.55464609, 1.35212423, 2.98060237, 2.38530123],
       [2.50428005, 1.23243317, 1.17200144, 2.33124922, 1.65914271],
       [1.72330124, 2.052222  , 1.84945992, 2.63956146, 2.14256949]])

In [43]:
np.random.normal(size=(3, 4)) # randn() 함수와 비슷하지만, 튜플을 인자로 받는다는 점에서 차이가 있습니다.
np.random.randn(3, 4)

array([[-0.13368054, -1.3610901 , -1.30022534,  0.01004113],
       [-1.05368742, -0.91878414,  0.00852071,  1.01270555],
       [-1.87120247,  0.85779193, -0.93330128,  0.26973425]])