## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.87090286 0.69496496 0.00108692 0.40488989 0.24265174]
 [0.83095745 0.61049718 0.61151208 0.42166137 0.1052413 ]
 [0.71935833 0.53361872 0.32687306 0.66811488 0.60189866]]


#### 연산 함수
 - add, substract, multiply, divide

In [3]:
np.add(x, y)

array([[ 0.87090286,  1.69496496,  2.00108692,  3.40488989,  4.24265174],
       [ 5.83095745,  6.61049718,  7.61151208,  8.42166137,  9.1052413 ],
       [10.71935833, 11.53361872, 12.32687306, 13.66811488, 14.60189866]])

In [4]:
np.divide(x, y)

array([[0.00000000e+00, 1.43892146e+00, 1.84006218e+03, 7.40942180e+00,
        1.64845304e+01],
       [6.01715530e+00, 9.82805522e+00, 1.14470348e+01, 1.89725704e+01,
        8.55177590e+01],
       [1.39012779e+01, 2.06139694e+01, 3.67114988e+01, 1.94577315e+01,
        2.32597293e+01]])

In [5]:
x + y

array([[ 0.87090286,  1.69496496,  2.00108692,  3.40488989,  4.24265174],
       [ 5.83095745,  6.61049718,  7.61151208,  8.42166137,  9.1052413 ],
       [10.71935833, 11.53361872, 12.32687306, 13.66811488, 14.60189866]])

In [6]:
x / y

array([[0.00000000e+00, 1.43892146e+00, 1.84006218e+03, 7.40942180e+00,
        1.64845304e+01],
       [6.01715530e+00, 9.82805522e+00, 1.14470348e+01, 1.89725704e+01,
        8.55177590e+01],
       [1.39012779e+01, 2.06139694e+01, 3.67114988e+01, 1.94577315e+01,
        2.32597293e+01]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [7]:
print(y)

[[0.87090286 0.69496496 0.00108692 0.40488989 0.24265174]
 [0.83095745 0.61049718 0.61151208 0.42166137 0.1052413 ]
 [0.71935833 0.53361872 0.32687306 0.66811488 0.60189866]]


In [8]:
np.mean(y)

0.5096152933815481

In [9]:
y.mean()

0.5096152933815481

In [10]:
np.max(y)

0.8709028563893685

In [11]:
np.argmax(y)

0

In [12]:
np.var(y), np.median(y), np.std(y)

(0.060826515666521724, 0.6018986635350743, 0.2466303218716663)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [13]:
y

array([[0.87090286, 0.69496496, 0.00108692, 0.40488989, 0.24265174],
       [0.83095745, 0.61049718, 0.61151208, 0.42166137, 0.1052413 ],
       [0.71935833, 0.53361872, 0.32687306, 0.66811488, 0.60189866]])

In [14]:
np.sum(y, axis=None) # axis=None은 전체의 합을 구한다

7.644229400723222

In [15]:
np.cumsum(y)

array([0.87090286, 1.56586782, 1.56695474, 1.97184463, 2.21449637,
       3.04545382, 3.655951  , 4.26746308, 4.68912444, 4.79436574,
       5.51372407, 6.04734279, 6.37421585, 7.04233074, 7.6442294 ])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [18]:
z = np.random.randn(10)
print(z)

[ 1.23558651 -0.68366446  0.03080394  0.88061263  0.19973678 -1.22771827
  0.25539343  0.54995942  0.64247153  0.06504149]


In [19]:
z > 0

array([ True, False,  True,  True,  True, False,  True,  True,  True,
        True])

In [20]:
np.any(z > 0)

True

In [21]:
np.all(z != 0)

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [22]:
z = np.random.randn(10)
print(z)

[ 0.1246229   1.09930714  0.86172812 -0.70287483 -0.28731306  0.60803053
  0.56550956  0.10484005  0.22398134 -0.44224691]


In [23]:
np.where(z > 0, z, 0)

array([0.1246229 , 1.09930714, 0.86172812, 0.        , 0.        ,
       0.60803053, 0.56550956, 0.10484005, 0.22398134, 0.        ])