## 학습목표
 1. axis의 이해
 2. axis를 파라미터로 갖는 함수 이해하기

In [1]:
import numpy as np

#### axis 이해하기
 - 몇몇 함수에는 axis keyword 파라미터가 존재
 - axis값이 없는 경우에는 전체 데이터에 대해 적용
 - axis값이 있는 경우에는, 해당 axis를 **따라서** 연산 적용

* axis를 파라미터로 갖는 함수를 이용하기
 - 거의 대부분의 연산 함수들이 axis 파라미터를 사용
 - 이 경우, 해당 값이 주어졌을 때, 해당 axis를 **따라서** 연산이 적용
   - 따라서 결과는 해당 axis가 제외된 나머지 차원의 데이터만 남게 됨
 - 예) np.sum, np.mean, np.any 등등
 

In [2]:
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


* 1차원 데이터에 적용하기

In [3]:
np.sum(x, axis=0)

105

In [4]:
np.sum(x, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

-1차원일때 axis는 0으로 설정한다

* 행렬에 적용하기

In [5]:
y = x.reshape(3, 5)
print(y)

np.sum(y, axis=0)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([15, 18, 21, 24, 27])

-행방향으로 0+5+10 ,1+6+11,... 더한다 

In [7]:
y = x.reshape(3, 5)
print(y)

np.sum(y, axis=1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([10, 35, 60])

-열방향으로 0+1+2+3+4,... 더한다

* 3차원 텐서에 적용하기

In [9]:
z = np.arange(36).reshape(3, 4, 3)
print(z)

np.sum(z, axis=0)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

-axis=0 는 0+12+24, 1+13+25 식으로 더한다

In [10]:
np.sum(z, axis=1)

array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

-axis=1 는 0+3+6+9,12+15+18+21 식으로 더한다

In [11]:
np.sum(z, axis=2)

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

-axis=2 는 0 + 1 + 2,3 + 4 + 5 식으로 더한다

In [12]:
np.sum(z, axis=-3)

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

* axis의 값이 튜플일 경우
 - 해당 튜플에 명시된 모든 axis에 대해서 연산

In [14]:
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [15]:
np.sum(z, axis=(0, 2))

array([117, 144, 171, 198])