## 학습목표
 1. 브로드캐스팅의 이해

In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.0327375  0.23166226 0.65802582 0.04829123 0.15935635]
 [0.78835607 0.05521843 0.14429995 0.3082023  0.26722281]
 [0.00842942 0.24848921 0.92828939 0.24203148 0.11830073]]


In [3]:
x * y

array([[ 0.        ,  0.23166226,  1.31605163,  0.1448737 ,  0.63742542],
       [ 3.94178036,  0.3313106 ,  1.01009963,  2.46561837,  2.40500533],
       [ 0.08429418,  2.73338135, 11.13947272,  3.14640925,  1.65621029]])

* Scalar(상수)와의 연산

In [4]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Shape이 다른 경우 연산

In [9]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

print(a.shape)
print(b.shape)
print(b)
print(c.shape)
print(d.shape)
print(d)

(4, 3)
(3,)
[100 101 102]
(4,)
(1, 3)
[[100 101 102]]


In [6]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [7]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [8]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])