## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [3]:
x = np.random.rand(3, 3, 3)
print(x)

np.matmul(x, np.linalg.inv(x))
x @ np.linalg.inv(x)

[[[0.05352363 0.90608624 0.20425633]
  [0.91262925 0.57798162 0.83937425]
  [0.19861169 0.62654011 0.49996077]]

 [[0.17922958 0.07939039 0.29449494]
  [0.02407733 0.1720129  0.23787857]
  [0.01963235 0.35015246 0.87659066]]

 [[0.67170632 0.18875835 0.51762355]
  [0.30932696 0.21532975 0.11752322]
  [0.46392822 0.83647661 0.64107955]]]


array([[[ 1.00000000e+00, -2.77555756e-17, -1.11022302e-16],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [-2.22044605e-16, -5.55111512e-17,  1.00000000e+00]],

       [[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-1.38777878e-17,  1.00000000e+00, -1.11022302e-16],
        [-5.55111512e-17,  0.00000000e+00,  1.00000000e+00]],

       [[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 5.55111512e-17,  1.00000000e+00, -2.77555756e-17],
        [ 0.00000000e+00,  4.44089210e-16,  1.00000000e+00]]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [4]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

np.allclose(A@x, B)

[18.  7.]


True