### 학습목표
 - 연습문제 풀이

#### 연습문제
 1. 로또 번호 자동 생성기(함수로)를 만드시오
 2. numpy를 이용하여 pi(원주율) 값을 계산하시오
  - 몬테 카를로 방법 이용하기
  - ![파이 값 구하기](http://mathfaculty.fullerton.edu/mathews/n2003/montecarlopi/MonteCarloPiMod/Images/MonteCarloPiMod_gr_25.gif)
  - 이미지 출처: http://mathfaculty.fullerton.edu/mathews/n2003/montecarlopi/MonteCarloPiMod/Images/MonteCarloPiMod_gr_25.gif 

In [1]:
import numpy as np

In [2]:
def generate_lotto_nums():
    return np.random.choice(np.arange(1, 46), size=6, replace=False) #replace=False는 숫자 중복 제거함
    
generate_lotto_nums()

array([27, 39, 35, 31, 13, 42])

pi/4 : 1 = (4분원 안에 생성된 점 개수) : 전체  시도 횟수

pi = 4 * (4분원 안에 생성된 점 개수) / 1e7

In [7]:
total = int(1e7)
points = np.random.rand(total, 2)
np.sum(points ** 2, axis=1)#axis=1 은 열로 더해준다 -> 1차원 벡터로 변경됨

array([0.41993823, 0.35005222, 0.41861584, ..., 0.77581032, 0.92564002,
       0.12643281])

In [6]:
total = int(1e7)
points = np.random.rand(total, 2)
np.sum(points ** 2, axis=1) < 1 #axis=1 은 열로 더해준다 -> 1차원 벡터로 변경됨

array([False,  True, False, ..., False,  True,  True])

In [3]:
total = int(1e7)
points = np.random.rand(total, 2)
4 * np.sum(np.sum(points ** 2, axis=1) < 1) / total #axis=1 은 열로 더해준다 -> 1차원 벡터로 변경됨

3.1410564

pi = 4 * (4분원 안에 생성된 점 개수) / 1e7